### ISSUE TITLE
CommandBar

### ISSUE THREAD

**Issue by MikeGTi** [jceresearch/onenote_vba_host#6]
For creating command bar in Office simple You can edit Ribbon file (customUI.xml/customUI14.xml) (RibbonXMLEditor, help to do it)

**Comment by jceresearch** [comment]
I didn't add a custom ribbon but a custom toolbar and seems to be still working in the excel version i have (max 2 months old) 
Have you checked this? 

https://excelrocks.com/a-step-by-step-guide-to-make-a-custom-toolbar-in-excel-with-vba/

**Comment by jceresearch** [comment]
For portability (and frankly because I wouldn't be able to do it via pure xml) the method for creating a toolbar would remain as is, ie adding a toolbar on load and deleting it on workbook close. There is a small routine for manually removing all custom toolbars, you might want to look at adding it to your fork to cleanup previous crashes, but it if you have other custom toolbars that would delete those too. Hope it helps!
